# Generated by Django 3.1.6 on 2022-09-21 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('feature_one', models.CharField(blank=True, max_length=100, null=True)),
                ('feature_two', models.CharField(blank=True, max_length=100, null=True)),
                ('feature_three', models.CharField(blank=True, max_length=100, null=True)),
                ('feature_four', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium', models.BooleanField(default=False)),
                ('cancel_membership', models.BooleanField(default=False)),
                ('subscription_date', models.DateField(blank=True, null=True)),
                ('expiration_data', models.DateField(blank=True, null=True)),
                ('plans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vpn.plan')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
