# Generated by Django 3.1.6 on 2022-09-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0003_membership_sluged'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='payment_completed',
            field=models.BooleanField(default=False),
        ),
    ]
