# Generated by Django 3.1.6 on 2022-09-22 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0004_membership_payment_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_duration_months',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
    ]
