# Generated by Django 3.1.6 on 2022-09-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0005_plan_plan_duration_months'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=10)),
                ('hostname', models.CharField(max_length=100)),
                ('server_username', models.CharField(max_length=100)),
                ('server_password', models.CharField(max_length=100)),
                ('flag_code', models.CharField(max_length=50)),
                ('premium_server', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='premium',
            new_name='premium_membership',
        ),
    ]
