# Generated by Django 4.1.1 on 2022-09-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0009_emailtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtoken',
            name='expiration_time',
            field=models.DateTimeField(),
        ),
    ]
