# Generated by Django 4.1.1 on 2022-09-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0011_alter_emailtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtoken',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
