# Generated by Django 4.1.1 on 2022-09-28 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0013_alter_emailtoken_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtoken',
            name='updated_at',
        ),
    ]
