# Generated by Django 4.1.1 on 2022-09-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0014_remove_emailtoken_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtoken',
            name='expiration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
